# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StudentGPADatabase(object):
    def setupUi(self, StudentGPADatabase):
        StudentGPADatabase.setObjectName("StudentGPADatabase")
        StudentGPADatabase.resize(689, 517)
        self.centralwidget = QtWidgets.QWidget(parent=StudentGPADatabase)
        self.centralwidget.setObjectName("centralwidget")
        self.student_ID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.student_ID.setGeometry(QtCore.QRect(240, 40, 113, 21))
        self.student_ID.setObjectName("student_ID")
        self.num_classes = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.num_classes.setGeometry(QtCore.QRect(240, 70, 113, 21))
        self.num_classes.setObjectName("num_classes")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 40, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 70, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(70, 410, 521, 21))
        self.label_message.setText("")
        self.label_message.setObjectName("label_message")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 110, 631, 291))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 629, 289))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.course_input_container = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.course_input_container.setEnabled(True)
        self.course_input_container.setObjectName("course_input_container")
        self.verticalLayout.addWidget(self.course_input_container)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.button_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_save.setGeometry(QtCore.QRect(290, 430, 113, 32))
        self.button_save.setObjectName("button_save")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(380, 50, 113, 32))
        self.submit_button.setObjectName("submit_button")
        StudentGPADatabase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=StudentGPADatabase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 24))
        self.menubar.setObjectName("menubar")
        self.menuStudent_GPA_Database = QtWidgets.QMenu(parent=self.menubar)
        self.menuStudent_GPA_Database.setObjectName("menuStudent_GPA_Database")
        StudentGPADatabase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=StudentGPADatabase)
        self.statusbar.setObjectName("statusbar")
        StudentGPADatabase.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuStudent_GPA_Database.menuAction())

        self.retranslateUi(StudentGPADatabase)
        QtCore.QMetaObject.connectSlotsByName(StudentGPADatabase)

    def retranslateUi(self, StudentGPADatabase):
        _translate = QtCore.QCoreApplication.translate
        StudentGPADatabase.setWindowTitle(_translate("StudentGPADatabase", "MainWindow"))
        self.label.setText(_translate("StudentGPADatabase", "Student ID:"))
        self.label_2.setText(_translate("StudentGPADatabase", "Number of Classes:"))
        self.button_save.setText(_translate("StudentGPADatabase", "Submit"))
        self.submit_button.setText(_translate("StudentGPADatabase", "Submit"))
        self.menuStudent_GPA_Database.setTitle(_translate("StudentGPADatabase", "Student GPA Database"))
